server:
  port: 9090
spring:
  application:
    name: CLOUD-GATEWAY

  cloud:
    gateway:
      routes:

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**
          filters:
            - AuthenticationFilter

        - id: ORDER-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

        - id: PAYMENT-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter


        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/