server:
  port: 9090
spring:
  application:
    name: CLOUD-GATEWAY

  cloud:
    gateway:
      routes:

        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - AuthenticationFilter

        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/